### ISSUE TITLE
On Archlinux

### ISSUE THREAD

**Issue by cderory** [tomneda/DABstar#1]
Hi Thomas,
I'm a French electronic teacher and I'm very interested with DABstar.
I work on Archlinux.
I succeeded with "cmake, make and make install".
When I run dabstar the GUI opens with 2 windows but I get the following messages :

[cderory@archlinux build]$ dabstar
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: too many profiles
spectrumViewer gezet op 100 100, staat op 100 100
libtii-lib.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
/usr/local/lib/tii-lib.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
Library not loaded
init_tii_L not loaded
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: too many profiles
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Suggested size for outputbuffer = 0
stream opened
stream started
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: too many profiles
Erreur de segmentation (core dumped)

The last line "Erreur de segmentation (core dumped)" is when I close the application in the normal way.

Regards

Cyrille DERORY
Email : cyrille@derory.fr

**Comment by tomneda** [comment]
Hello Cyrille,

thanks that you are interested in DABstar.

I never tried a `make install` yet but I did recently. Unfortunately, at my side it failed already while startup. I guess the problem on my side is that I use a new QT version while build. Running the installed `dabstar` tries to find and use the Qt version which is provided by the Linux distribution (I use Xubuntu 22.04) and the< are not compatible. But running `./dabstar` from the build folder works fine.

At your side it seems that the program is working but you are worried about the warnings and the final core dump?

I have the libpng and ALSA warnings also (very likely also with the original Qt-DAB) and they come from the used external library I guess. I am quite sure you can ignore them.

But I will try to find out the reason for the warnings and get rid of them.

The `libtii-lib.so` is a external library which could be installed by hand, but Jan's Qt-DAB has provided its own library which works fine. If you installed the file .txdata.tii in your home folder correctly, you should see line
`tiiFile is /home/<yourHome>/.txdata.tii`.
See https://github.com/JvanKatwijk/qt-dab/blob/master/README.md#step-4 for more details here.
(I just see that the tiiFile.zip is missing in my repository, please use that from Qt-DAB meanwhile: https://github.com/JvanKatwijk/qt-dab/blob/master/tiiFile.zip).

For the core dump: here at my side I have not such issue. Do you still see it, if you run ./dabstar directly in the build folder?

I got these outputs when I start .`/dabstar`, run it and finish it:
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: too many profiles
spectrumViewer gezet op 0 0, staat op 0 0
libtii-lib.so: cannot open shared object file: No such file or directory
/usr/local/lib/tii-lib.so: cannot open shared object file: No such file or directory
Library not loaded
init_tii_L not loaded
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: too many profiles
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Suggested size for outputbuffer = 0
stream opened
stream started
tiiFile is /home/work/.txdata.tii
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: too many profiles
OK, functions seem to be loaded
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Supported gain values (29): 49.6 48.0 44.5 43.9 43.4 42.1 40.2 38.6 37.2 36.4 33.8 32.8 29.7 28.0 25.4 22.9 20.7 19.7 16.6 15.7 14.4 12.5 8.7 7.7 3.7 2.7 1.4 0.9 0.0 
[R82XX] PLL not locked!
Realtek RTL2838UHIDIR 00000001
channel reset: all services will be stopped
München/Olympiaturm 7 km 15 ° 
going to open ANTENNE BAYERN  
we have now 1 backends running
DabProcessor is stopping
closing on freq 222064000
.. end the radio silences
back in main program
radioInterface is deleted
```

Maybe you should try build Qt-DAB? Do you have the core dump there, too?

You could try to provide a output of the dump file. I guess it contains better information when you build DABstar with debug information with `-DCMAKE_BUILD_TYPE=Debug` on the `cmake` command line.

Best Regards
Thomas

**Comment by tomneda** [comment]
I will close this now. You are welcome to ask for help again.
