### ISSUE TITLE
Download of TII data fails

### ISSUE THREAD

**Issue by old-dab** [tomneda/DABstar#17]
I switched from Linux Mint 21 to 22 (based on Ubuntu 24.04). Since then, the download of .rxdata.tii no longer works.
Qt-Dab has a newer libtii-lib.so that works.

**Comment by tomneda** [comment]
@old-dab strange things are happening, but from beginning:

I upgraded also lately from Xubuntu 22.04 to 24.04 but the download of the `.txdata.tii` (to the home directory) still works on my side.
(you said `.rxdata.tii` above but I guess you meant `.txdata.tii`)

The regarding library `libtii-lib.so` is still copied to `/usr/local/lib` where DABstar can find it.
See https://github.com/tomneda/DABstar/blob/main/tii-library/
Is it also that case on your side?

But nevertheless I looked at the newest Qt-DAB stuff and there in https://github.com/JvanKatwijk/qt-dab/tree/master/library the `libtii-lib.so` has really changed. 

Simply exchanging it with the older one was not working. The library interface has changed completely (got much more simple). I adapt my code also to access this interface according the the code in Qt-DAB repository. The loading and call to the lib works but it produced no (new) `.txdata.tii` file in the home folder. Additionally, there is an error handling missing with the new lib (or how it was accessed) so DABstar would still say wrongly _"Loading and installing database complete"_. So this was unsatisfactory.

Then I started the latest Qt-DAB AppImage and clicked "Load Table", and it generates a new `.txdata.tii` in the home folder. Also with the exactly same binary content as DABstar does with the older library. Strange.

I did some analysis what the AppImage of Qt-DAB makes here and it seems that Qt-DAB does not use the `libtii-lib.so` at all. It looks like that it executes this in a different way than I could see it in the repository code. But I do not want to dig into that further.

So in short you could try following:

For me the old `libtii-lib.so` is still working but with your upgrade is it either got deleted or the recommend path in https://github.com/tomneda/DABstar/blob/main/tii-library/README.txt to `/usr/local/lib/` is not more in the library search path (but I would wonder). *1) *2)

or your try this:

Qt-DAB (the AppImage) seems not using the library anymore, so (currently) there is no need yet copying the Qt-DAB library file to there.
As Qt-DAB generates the file `.txdata.tii` still compatible to DABstar you can generate it with Qt-DAB and DABstar should work with that. *3)

*1) As I see in the DABstar code it tries first looking for `libtii-lib.so` first in its local working folder. If you build DABstar for yourself it should work to place the lib side-by-side to the `dabstar` executable (but I did not tried that).

*2) If the old lib is existing but will still not work maybe you could analyze it with `ldd libtii-lib.so` and check if some dependency lib is missing?

*3) It seems there could be an unwanted dependency between Qt-DAB and DABstar I will think of it doing it better in future. Qt-DAB evolves further after my branching off it longer ago and it got difficult to keep compatibility in some cases.

**Comment by old-dab** [comment]
Sorry, I meant .txdata.tii
In the meanwhile, download of .txdata.tii with DABstar here works again.
I don't know the reason. Maybe because I started the "Aktualisierungsverwaltung" of Linux Mint, which updated a lot of software.
