### ISSUE TITLE
Make course frequency correction more robust

### ISSUE THREAD

**Issue by tomneda** [tomneda/DABstar#22]
Regarding issue https://github.com/tomneda/DABstar/issues/19 it would be good that the coarse frequency correction does not only correct the input LO frequency resp. baseband frequency offset but considered the reference frequency of the device (also). This is necessary because of the drift in the sample frequency is not considered with only changing the LO resp. baseband frequency offset.

**Comment by old-dab** [comment]
I have a suggestion for this issue: https://github.com/old-dab/DABstar/commit/227ca29078d5072df174b822cf0f54c5c26f77e2
This allows synchronization up to +-150ppm deviation.
However, there is another problem with USB sticks with separate quartz crystals for tuner and RTL2832, such as the Astrometa. The ppm correction affects both quartz crystals. So you have to decide whether you want the exact frequency or symbol rate. My worst USB stick needs +80ppm in the tuner quartz crystal and -50ppm in the RTL quartz crystal. A correct symbol rate seems to be better, as you can see in the pictures below.

![Dexatek+80ppm](https://github.com/user-attachments/assets/90848d99-2912-4580-88c9-94bddc9d9d64)
![Dexatek-51ppm](https://github.com/user-attachments/assets/ea2062c7-e28f-4a6d-9647-9640098e5f5b)

**Comment by tomneda** [comment]
@old-dab : I tried out your version and it really performs much better. So I take it over but not all changes because I will maintain the "DC avoidance algorithm" which you removed. But it is still working well.

I wonder about the construct with the `abs()` method. I thought this is correlation sum and so also negative values should be summed ab.
```
  int16_t index = IDX_NOT_FOUND;
  {
    float MMax = 0;

    for (int16_t i = 0; i < SEARCHRANGE; i++)
    {
      float sum = 0;
      for (int16_t j = 0; j < CORRELATION_LENGTH; ++j)
      {
        sum += abs(mRefArg[j] * mCorrelationVector[i + j]);  // why this abs() method?
        if (sum > MMax)
        {
          MMax = sum;
          index = i;
        }
      }
    }
  }

```
Without this abs() method (which I would assume as more correct) it works also but a bit less reliable. Maybe you can explain the technical background of this part in the code?

Motivated with your changes I tried out other methods for frequency estimation and I found also one which performs similar; and I understand it better why it performs so :smiley: 

But I want try out a bit more before you could see the results. I did not pushed the adaptions back if you liked to see them.

**Comment by old-dab** [comment]
In found these lines here in the processPRS function: https://github.com/AlbrechtL/welle.io/blob/master/src/backend/ofdm-processor.cpp

**Comment by tomneda** [comment]
@old-dab : I implement your proposal (and more from your fork) into Version 3.0.1: 
https://github.com/tomneda/DABstar/releases/tag/V3.0.1

Coarse frequency correction works much better now and so I will close this now.

I see that you do many further improvements in your DABstar fork I would like to have also in my version. I try to takeover your parts but it is a kind of tedious work. What do you think to make pull request to me for that to maintain only one version of DABstar? 😃

I would be delighted if you contact me private: thomas dot neder at freenet dot de (you can write German then if you want).

BR Thomas
