### ISSUE TITLE
Service Label change

### ISSUE THREAD

**Issue by andimik** [tomneda/DABstar#23]
When the service label changes (here in Austria `OE24 - AUSTRIA` renamed just to `OE24`), the program will still keep the old name in the list, but won't play any sound.
![grafik](https://github.com/user-attachments/assets/5a915482-95f9-4686-aba4-e2f352ffe549)

[dabstar.zip](https://github.com/user-attachments/files/17498717/dabstar.zip)

**Comment by tomneda** [comment]
@andimik : Interesting issue. I could somehow reproduce it here with your provided database file. But I currently have not much time to check this in detail but please let this issue open to remember me for this later.
I think it is only a minor thing. A whole re-scan should repair this.

**Comment by andimik** [comment]
https://www.digitalbitrate.com/dtv.php?mux=11C&liste=1&live=153&lang=en

You could test it even in Munich, channel 11C.

**Comment by tomneda** [comment]
@andimik : Yes I saw it. "LORA MUENCHEN" and "RADIO FEIERWERK" exchange they places. To solve this I need a feature to delete also entries from the database (without restarting a new scan). Not too easy to handle this but I will do it.
At least new service names are added to the database, so you should not miss an entry.

**Comment by tomneda** [comment]
@andimik : I did a fix among other things in V3.0.1.

https://github.com/tomneda/DABstar/releases/tag/V3.0.1
